
2023-01-09 14:15:25.507019: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-09 14:15:25.521161: wfastcgi.py 3.0.0 initialized
2023-01-09 14:16:18.624240: wfastcgi.py exiting because company.py has changed, matching .*((\.py)|(\.config))$
2023-01-09 14:16:18.635226: Running on_exit tasks
2023-01-09 14:17:43.815169: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported


StdOut: 

StdErr: 
2023-01-09 14:17:43.831795: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
2023-01-09 14:17:43.845788: Running on_exit tasks
2023-01-09 14:17:43.860787: wfastcgi.py 3.0.0 closed
2023-01-09 14:17:47.802038: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported


StdOut: 

StdErr: 
2023-01-09 14:17:47.819006: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
2023-01-09 14:17:47.834998: Running on_exit tasks
2023-01-09 14:17:47.847989: wfastcgi.py 3.0.0 closed
2023-01-09 14:17:54.147253: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported


StdOut: 

StdErr: 
2023-01-09 14:17:54.163245: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
2023-01-09 14:17:54.183240: Running on_exit tasks
2023-01-09 14:17:54.198225: wfastcgi.py 3.0.0 closed
2023-01-09 14:18:41.952074: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported


StdOut: 

StdErr: 
2023-01-09 14:18:41.971065: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\company.py", line 6, in <module>
    mydb = connection.MySQLConnection(user='root', password='sp224466',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\abstracts.py", line 716, in connect
    self._open_connection()
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\connection.py", line 137, in _do_auth
    packet = self._protocol.make_auth(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 99, in make_auth
    packet += self._auth_response(client_flags, username, password,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FlaskApp\env\Lib\site-packages\mysql\connector\authentication.py", line 190, in get_auth_plugin
    raise errors.NotSupportedError(
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
2023-01-09 14:18:41.988055: Running on_exit tasks
2023-01-09 14:18:42.004046: wfastcgi.py 3.0.0 closed
2023-01-09 14:20:43.872969: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-09 14:20:43.881966: wfastcgi.py 3.0.0 initialized
2023-01-09 14:39:09.453041: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-09 14:39:09.472725: wfastcgi.py 3.0.0 initialized
2023-01-09 15:55:24.082228: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-09 15:55:24.097219: wfastcgi.py 3.0.0 initialized
2023-01-09 16:08:19.881267: wfastcgi.py exiting because company.py has changed, matching .*((\.py)|(\.config))$
2023-01-09 16:08:19.895258: Running on_exit tasks
2023-01-09 16:09:42.667722: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-09 16:09:42.681713: wfastcgi.py 3.0.0 initialized
2023-01-10 10:06:50.542456: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-10 10:06:50.552471: wfastcgi.py 3.0.0 initialized
2023-01-11 10:54:45.270249: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-11 10:54:45.282512: wfastcgi.py 3.0.0 initialized
2023-01-11 15:12:27.064523: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-11 15:12:27.073495: wfastcgi.py 3.0.0 initialized
2023-01-15 18:27:15.540667: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-15 18:27:15.540667: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-15 18:27:15.692652: wfastcgi.py 3.0.0 initialized
2023-01-17 09:49:39.296114: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-17 09:49:39.322674: wfastcgi.py 3.0.0 initialized
2023-01-17 11:16:26.606440: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-17 11:16:26.637425: wfastcgi.py 3.0.0 initialized
2023-01-18 11:56:02.453155: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-18 11:56:02.483145: wfastcgi.py 3.0.0 initialized
2023-01-18 12:21:06.185199: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-18 12:21:06.214153: wfastcgi.py 3.0.0 initialized
2023-01-18 12:32:04.683068: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-18 12:32:04.692063: wfastcgi.py 3.0.0 initialized
2023-01-18 12:40:28.455124: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-18 12:40:28.465095: wfastcgi.py 3.0.0 initialized
2023-01-19 10:51:24.747758: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-01-19 10:51:24.805513: wfastcgi.py 3.0.0 initialized
2023-06-23 10:30:07.966315: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-06-23 10:30:07.987302: wfastcgi.py 3.0.0 initialized
2023-06-23 11:30:40.518841: wfastcgi.py will restart when files in C:\FlaskApp\ are changed: .*((\.py)|(\.config))$
2023-06-23 11:30:40.539400: wfastcgi.py 3.0.0 initialized
